[project]
  name         = "pi66.xyz"
  version      = "0.3.0"
  description  = "my main website"

[tree]
  markdown     = "md"
  templates    = "src/templates"
  plugins      = "src/plugins"
  draft_dest   = "draft"
  release_dest = "/srv/www/pi66.xyz/public/html"
